name = "chandev"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "STATIC_ASSETS"
directory = "dist/client"

[[kv_namespaces]]
binding = "SESSION"
id = "c2ae35eea2864cc5b5b9819edc49473d"

[vars]
WORKOS_REDIRECT_URI = "https://chan.dev/auth/callback"
WORKOS_CLIENT_ID = "client_01HRBZRK6DZZ4FK5YAFNE4K388"
